import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 1. Getting Started',
    },
    {
      type: 'category',
      label: '🐳 2. Docker Fundamentals',
      items: [
        {type: 'autogenerated', dirName: 'docker-basics'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-fundamentals',
        title: 'Docker Fundamentals'
      },
    },
    {
      type: 'category',
      label: '⚡ 3. Docker CLI Commands',
      items: [
        {type: 'autogenerated', dirName: 'docker-cli'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-cli',
        title: 'Docker CLI'
      },
    },
    {
      type: 'category',
      label: '📝 4. Dockerfiles',
      items: [
        {type: 'autogenerated', dirName: 'dockerfiles'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/dockerfiles',
        title: 'Dockerfiles'
      },
    },
    {
      type: 'category',
      label: '🧩 5. Docker Compose',
      items: [
        {type: 'autogenerated', dirName: 'docker-compose'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-compose',
        title: 'Docker Compose'
      },
    },
    {
      type: 'category',
      label: '🏗️ 6. Docker Custom Images',
      items: [
        {type: 'autogenerated', dirName: 'docker-custom-images'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-custom-images',
        title: 'Docker Custom Images'
      },
    },
    {
      type: 'category',
      label: '🌐 7. Docker Networking',
      items: [
        {type: 'autogenerated', dirName: 'docker-networking'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-networking',
        title: 'Docker Networking'
      },
    },
    {
      type: 'category',
      label: '📦 8. Docker Volumes',
      items: [
        {type: 'autogenerated', dirName: 'docker-volumes'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-volumes',
        title: 'Docker Volumes'
      },
    },
    {
      type: 'category',
      label: '🧭 9. Docker Orchestration',
      items: [
        {type: 'autogenerated', dirName: 'docker-orchestration'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-orchestration',
        title: 'Docker Orchestration'
      },
    },
    {
      type: 'category',
      label: '👨‍💻 10. Docker for Developers',
      items: [
        {type: 'autogenerated', dirName: 'docker-for-developers'},
      ],
      link: {
        type: 'generated-index',
        slug: '/category/docker-for-developers',
        title: 'Docker for Developers'
      },
    },
  ],
};

export default sidebars;