import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 1. Getting Started',
    },
    {
      type: 'category',
      label: '🐳 2. Docker Fundamentals',
      items: [
        {type: 'autogenerated', dirName: 'docker-basics'},
      ],
    },
    {
      type: 'category',
      label: '⚡ 3. Docker CLI Commands',
      items: [
        {type: 'autogenerated', dirName: 'docker-cli'},
      ],
    },
    {
      type: 'category',
      label: '📝 4. Dockerfiles',
      items: [
        {type: 'autogenerated', dirName: 'dockerfiles'},
      ],
    },
    {
      type: 'category',
      label: '🧩 5. Docker Compose',
      items: [
        {type: 'autogenerated', dirName: 'docker-compose'},
      ],
    },
    {
      type: 'category',
      label: '🏗️ 6. Docker Custom Images',
      items: [
        {type: 'autogenerated', dirName: 'docker-custom-images'},
      ],
    },
    {
      type: 'category',
      label: '🌐 7. Docker Networking',
      items: [
        {type: 'autogenerated', dirName: 'docker-networking'},
      ],
    },
    {
      type: 'category',
      label: '📦 8. Docker Volumes',
      items: [
        {type: 'autogenerated', dirName: 'docker-volumes'},
      ],
    },
    {
      type: 'category',
      label: '🧭 9. Docker Orchestration',
      items: [
        {type: 'autogenerated', dirName: 'docker-orchestration'},
      ],
    },
    {
      type: 'category',
      label: '👨‍💻 10. Docker for Developers',
      items: [
        {type: 'autogenerated', dirName: 'docker-for-developers'},
      ],
    },
  ],
};

export default sidebars;